#!/usr/bin/env python3

import sys

def main(word=None):
    word = sys.argv[1].upper() if (word is None) else word
    size = len(word)
    print(".LINK %s 0x%04X ; Header with flags and length" % (word, size))
    print("  DAT ", end="")
    if size % 2:
        word += "\x00"
    pairs = [word[i:i+2] for i in range(0, size, 2)]
    for pair in pairs:
        print("0x%02X%02X " % (ord(pair[0]), ord(pair[1])), end="")
    print("; " + " ".join('"%s"' % repr(pair)[1:-1] for pair in pairs))
    print(":%s" % word)

if __name__ == "__main__":
    main()
